
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check and update tsconfig.json
        run: |
          if ! jq '.compilerOptions.esModuleInterop' tsconfig.json | grep -q true; then
            jq '.compilerOptions.esModuleInterop = true' tsconfig.json > tmp.json && mv tmp.json tsconfig.json
          fi
      - name: Install jest-silent-reporter
        run: npm install --save-dev jest-silent-reporter --legacy-peer-deps

      - name: Run unit tests with coverage
        run: npm run test:coverage -- --watch=false --verbose
        env:
          JEST_SILENT_REPORTER_SHOW_SUMMARY: false
          JEST_SILENT_REPORTER_SHOW_COVERAGE: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/angular-starter

  sonar-qube:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: b6d5941dfedcb1b62a5a6cdf4921ad0c954f06c3
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=neelameghashyam_code-book-playwright
            -Dsonar.organization=neelameghashyam
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/dist/**
  deploy:
    needs: sonar-qube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/angular-starter

      - name: Deploy to Netlify
        run: npx netlify deploy --dir=dist/angular-starter/browser --prod
        env:
          NETLIFY_AUTH_TOKEN: nfp_TvXtA8181JNEU9yex1c82aQN6k1XCwis0de9
          NETLIFY_SITE_ID: 33ce5c86-9de6-41e0-952f-b0c4f60c0a67
